# Generated by Django 3.1.2 on 2020-10-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comment_body',
            field=models.CharField(max_length=200),
        ),
    ]
