# Generated by Django 3.1.2 on 2020-10-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20201015_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comment_body',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
